version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_data_repository_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_data_repository
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ai_data_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_data_repository"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai_data_repository_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ai_data_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ai_data_network:
    driver: bridge
